services:
  web:
    container_name: ${PROJECT_NAME}-web
    image: webdevops/php-apache-dev:8.3
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/app/web
      - WEB_DOCUMENT_INDEX=index.php
      - PHP_MAX_EXECUTION_TIME=86400
      - PHP_POST_MAX_SIZE=1024M
      - PHP_UPLOAD_MAX_FILESIZE=1024M
      - PHP_MEMORY_LIMIT=2048M
    ports:
      - "${DOCKER_APP_PORT}:80"
    networks:
      - ${PROJECT_NAME}-network
    depends_on:
      - db
  
  db:
    image: mariadb:10.3
    container_name: ${PROJECT_NAME}-db
    restart: on-failure
    ports:
      - "${DOCKER_MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    networks:
      - ${PROJECT_NAME}-network
    volumes:
      - ./.docker/data:/var/lib_/mysqlz'
  
  phpMyAdmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PROJECT_NAME}-phpmyadmin
    restart: always
    ports:
      - "${DOCKER_PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: ${PROJECT_NAME}-db
      PMA_USER: root
      PMA_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - ${PROJECT_NAME}-network

networks:
  manacas-network:
    driver: bridge
