<?php


namespace App\Controllers;

use Yii;
use App\Models\Logs;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\VarDumper;
use yii\web\BadRequestHttpException;

class BaseController extends \yii\web\Controller
{

    /**
     * @throws BadRequestHttpException
     */
    public function beforeAction($action): ?bool
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['/auth/login'])->send();
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function __construct($id, $module, $config = [])
    {
        parent::__construct($id, $module, $config);
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors(): array
    {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            $user = Yii::$app->user?->identity;
                            $controller = $action->controller->id;

                            if (!$user) {
                                return false;
                            }

                            // Bloquear completamente o controller 'user' para não-admins
                            if ($controller === 'users' && !$user->is_admin) {
                                return false;
                            }

                            // Apenas logado pode acessar (validado acima), mas o resto fica liberado
                            return true;
                        }
                    ],
                ],
            ],
        ];
    }
}
